"""
Django settings for sistema_escolar_api project.

Generated by 'django-admin startproject' using Django 2.2.
"""

import os

# ==========================
# RUTAS
# ==========================

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ==========================
# CONFIGURACIÓN BÁSICA
# ==========================

SECRET_KEY = '-_&+lsebec(whhw!%n@ww&1j=4-^j_if9x8$q778+99oz&!ms2'

# OJO: en producción debe ser False
DEBUG = True

# Añadimos localhost, Render y cualquier subdominio onrender.com
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'app-web-api.onrender.com',
    '.onrender.com',
]

# ==========================
# APPS
# ==========================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'corsheaders',

    'sistema_escolar_api',
]

# ==========================
# MIDDLEWARE
# ==========================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # CORS SIEMPRE ANTES DE CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==========================
# CORS
# ==========================

# Si quieres ser permisivo en lo que resta del semestre, puedes dejarlo en True.
# Si en algún momento lo quieres restringir, pon False y usa la lista de orígenes.
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

# Para versiones viejas de django-cors-headers, estas listas se usan;
# no estorban aunque tengas CORS_ORIGIN_ALLOW_ALL = True.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    # URL pública de tu front en Vercel (ajusta si cambia)
    "https://sistema-web-app.vercel.app",
    # Ejemplo de preview actual; puedes dejarla o actualizarla
    "https://sistema-web-hrnuokk5b-ivan-flores-projects-13ba27c6.vercel.app",
]

CORS_ORIGIN_WHITELIST = CORS_ALLOWED_ORIGINS

CORS_ORIGIN_REGEX_WHITELIST = [
    r"^http://localhost:4200$",
    r"^https://sistema-web-.*\.vercel\.app$",
]

# ==========================
# URLS / TEMPLATES / WSGI
# ==========================

ROOT_URLCONF = 'sistema_escolar_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_escolar_api.wsgi.application'

# ==========================
# BASE DE DATOS (LOCAL MYSQL)
# ==========================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sistema_escolar_db',
        'USER': 'root',
        'PASSWORD': '',  # pon tu contraseña aquí si la tienes
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# ==========================
# VALIDACIÓN DE PASSWORD
# ==========================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==========================
# I18N
# ==========================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ==========================
# ESTÁTICOS
# ==========================

STATIC_URL = '/static/'

# ==========================
# DRF
# ==========================

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'sistema_escolar_api.models.BearerTokenAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}
